language: php

php:
  - 7.3

env:
  global:
    - XDEBUG_MODE=coverage
    - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src
  - vendor/bin/codecept run --coverage-xml --env standalone
